# Generated by Django 2.2.1 on 2019-05-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('links', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='sended',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pic',
            name='sended',
            field=models.BooleanField(default=False),
        ),
    ]
